spring.application.name=uberApp

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=1234
#crate-drop is used when you want to drop the schema and start new everytime we run the app
spring.jpa.hibernate.ddl-auto=create


jwt.secretKey = aakjfsbdfjfen38vnsdg3irbe893buf8ehfw3o8qqewf97hw3rfaib98

#smp config
spring.mail.username=sahilshirodkar1630@gmail.com
spring.mail.password=qijf jkmo lwnb mimk
spring.mail.host=smtp.gmail.com
smtp.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true